-- AlterTable
ALTER TABLE "Agent" ADD COLUMN     "maxTokens" INTEGER NOT NULL DEFAULT 2048,
ADD COLUMN     "model" TEXT NOT NULL DEFAULT 'gemini-2.0-flash-exp',
ADD COLUMN     "temperature" DOUBLE PRECISION NOT NULL DEFAULT 0.7,
ADD COLUMN     "tools" TEXT[] DEFAULT ARRAY[]::TEXT[],
ADD COLUMN     "topP" DOUBLE PRECISION NOT NULL DEFAULT 0.9;
